export type CardName =
    | "Aeromancer"
    | "Air"
    | "Air Elemental"
    | "Angel"
    | "Archangel"
    | "Archmage"
    | "Ash"
    | "Astral Dragon"
    | "Basilisk"
    | "Battle Mage"
    | "Beast"
    | "Bird"
    | "Blizzard"
    | "Blue Knight"
    | "Bone"
    | "Colossus"
    | "Death"
    | "Death Sprite"
    | "Decay Demon"
    | "Demon"
    | "Demonologist"
    | "Devil"
    | "Dirigible"
    | "Dragon"
    | "Druid"
    | "Dryad"
    | "Earth"
    | "Earthquake"
    | "Enraged Beast"
    | "Enraged Demon"
    | "Entropic Magic"
    | "Explosion"
    | "Fairy"
    | "Fallen Angel"
    | "Fire"
    | "Fire Giant"
    | "Fire Golem"
    | "Fire Sprite"
    | "Fireball"
    | "Jackpot"
    | "Game"
    | "Geomancer"
    | "Ghost"
    | "Giant"
    | "Giant Snake"
    | "Golem"
    | "Green Knight"
    | "Harpy"
    | "High Vampire"
    | "Huge Snake"
    | "Human"
    | "Hydra"
    | "Hydromancer"
    | "Ice"
    | "Ice Imp"
    | "Infectious"
    | "Knight"
    | "Lava"
    | "Litch"
    | "Living Skeleton"
    | "Magic"
    | "Mechanical Angel"
    | "Mechanical Beast"
    | "Mechanical Golem"
    | "Mechanical Dragon"
    | "Mechanism"
    | "Mermaid"
    | "Metal"
    | "Mind Control"
    | "Mutation"
    | "Necromancer"
    | "Obsession"
    | "Plague"
    | "Playing Cards"
    | "Poison"
    | "Poisoner"
    | "Poisonous Dragon"
    | "Pyromancer"
    | "Red Knight"
    | "Sand Storm"
    | "Scrap Metal"
    | "Skeletal Dragon"
    | "Skeletal Snake"
    | "Snake"
    | "Spin the Bottle"
    | "Spirit"
    | "Tree"
    | "Undead"
    | "Undead Beast"
    | "Undead Giant"
    | "Undead Knight"
    | "Undead Mage"
    | "Unicorn"
    | "Vampire"
    | "Warrior Angel"
    | "Water"
    | "Water Dragon"
    | "Waterfall"
    | "Wind"
    | "Wind Demon"
    | "Wings"
    | "Wizard"
    | "Wooden Golem"
    | "Wraith"
    | "Wyvern"
    | "__UNKNOWN__";

export type CardRarity = "CR0" | "CR1" | "CR2" | "CR3" | "CR4";
